apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    name: db-service
    app: demo-voting-app
spec:
  ports:
      type: ClusterIP         # if not mentioned by default it will take ClusterIP
    - port: 5432
      targetPort: 5432
  selector:
    name: postgres-pod
    app: demo-voting-app